import { Component } from '@angular/core';
import { Navbar } from '@shared/layout/navbar/navbar';
import { Footer } from '@shared/layout/footer/footer';
import { ProductGrid } from '@features/catalog/components/product-grid/product-grid';
import { Product } from '@features/catalog/models/product';
import { Button } from '@shared/ui/button/button';

@Component({
  selector: 'app-catalog-page',
  imports: [Navbar, Footer, ProductGrid, Button],
  templateUrl: './catalog-page.html',
  styleUrl: './catalog-page.css',
})
export class CatalogPage {
  products: Product[] = [
    {
      id: 1,
      name: 'Soft minimal tote bag',
      description: 'Everyday tote with clean lines and soft-touch finish.',
      category: 'Dark',
      price: 590.00,
      discount: 200.00,
      tags: ['Editor’s pick'],
      imageUrl: 'product-image-1.avif',
      stock: 10,
    },
    {
      id: 2,
      name: 'Oversized wool blazer',
      description: 'Relaxed fit with sharp shoulders for day-to-night looks.',
      category: 'Dark',
      price: 120,
      tags: ['Best seller'],
      imageUrl: 'product-image-1.avif',
      stock: 5,
    },
    {
      id: 3,
      name: 'Oversized wool blazer',
      description: 'Relaxed fit with sharp shoulders for day-to-night looks.',
      category: 'Dark',
      price: 120,
      tags: ['Best seller'],
      imageUrl: 'product-image-1.avif',
      stock: 5,
    },
    {
      id: 4,
      name: 'Oversized wool blazer',
      description: 'Relaxed fit with sharp shoulders for day-to-night looks.',
      category: 'Dark',
      price: 120,
      tags: ['Best seller'],
      imageUrl: 'product-image-1.avif',
      stock: 5,
    },
    {
      id: 5,
      name: 'Oversized wool blazer',
      description: 'Relaxed fit with sharp shoulders for day-to-night looks.',
      category: 'Dark',
      price: 120,
      tags: ['Best seller'],
      imageUrl: 'product-image-1.avif',
      stock: 5,
    },
    {
      id: 6,
      name: 'Soft minimal tote bag',
      description: 'Everyday tote with clean lines and soft-touch finish.',
      category: 'Modern',
      price: 590.00,
      discount: 200.00,
      tags: ['Editor’s pick'],
      imageUrl: 'product-image-1.avif',
      stock: 10,
    },
    {
      id: 7,
      name: 'Oversized wool blazer',
      description: 'Relaxed fit with sharp shoulders for day-to-night looks.',
      category: 'Modern',
      price: 120,
      tags: ['Best seller'],
      imageUrl: 'product-image-1.avif',
      stock: 5,
    },
    {
      id: 8,
      name: 'Oversized wool blazer',
      description: 'Relaxed fit with sharp shoulders for day-to-night looks.',
      category: 'Modern',
      price: 120,
      tags: ['Best seller'],
      imageUrl: 'product-image-1.avif',
      stock: 5,
    },
    {
      id: 9,
      name: 'Oversized wool blazer',
      description: 'Relaxed fit with sharp shoulders for day-to-night looks.',
      category: 'Modern',
      price: 120,
      tags: ['Best seller'],
      imageUrl: 'product-image-1.avif',
      stock: 5,
    },
    {
      id: 10,
      name: 'Oversized wool blazer',
      description: 'Relaxed fit with sharp shoulders for day-to-night looks.',
      category: 'Modern',
      price: 120,
      tags: ['Best seller'],
      imageUrl: 'product-image-1.avif',
      stock: 5,
    },
    {
      id: 11,
      name: 'Soft minimal tote bag',
      description: 'Everyday tote with clean lines and soft-touch finish.',
      category: 'Woods',
      price: 590.00,
      discount: 200.00,
      tags: ['Editor’s pick'],
      imageUrl: 'product-image-1.avif',
      stock: 10,
    },
    {
      id: 12,
      name: 'Oversized wool blazer',
      description: 'Relaxed fit with sharp shoulders for day-to-night looks.',
      category: 'Woods',
      price: 120,
      tags: ['Best seller'],
      imageUrl: 'product-image-1.avif',
      stock: 5,
    },
    {
      id: 13,
      name: 'Oversized wool blazer',
      description: 'Relaxed fit with sharp shoulders for day-to-night looks.',
      category: 'Woods',
      price: 120,
      tags: ['Best seller'],
      imageUrl: 'product-image-1.avif',
      stock: 5,
    },
    {
      id: 14,
      name: 'Oversized wool blazer',
      description: 'Relaxed fit with sharp shoulders for day-to-night looks.',
      category: 'Woods',
      price: 120,
      tags: ['Best seller'],
      imageUrl: 'product-image-1.avif',
      stock: 5,
    },
    {
      id: 15,
      name: 'Oversized wool blazer',
      description: 'Relaxed fit with sharp shoulders for day-to-night looks.',
      category: 'Woods',
      price: 120,
      tags: ['Best seller'],
      imageUrl: 'product-image-1.avif',
      stock: 5,
    },
  ];
}
